<?php
$title = 'Les parcours';
$this->headTitle($title);
?>

<ul class="breadcrumb">
	<li><a href="<?php echo $this->url('page') ?>"> Accueil </a> <span class="divider">/</span></li>
    <li class="active">Parcours</li>
</ul>

<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css'); ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css'); ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/pillbox.css'); ?>

<!-- Help Modal -->
<div id="helpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Aide</h3>
    </div>
    <div class="modal-body">
    	<p>
    	Vous êtes sur la page principale de consultation des parcours.
    	</p>
    	<p>
    	Chaque ligne représente un parcours. Cliquez sur le titre d'un parcours pour accéder à ce parcours.
    	</p>
    	<p>
    	Si vous avez l'autorisation, vous pouvez créer un nouveau parcours avec le bouton en haut à droite.
    	</p>
    </div>
    <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="page-header row-fluid">
	<div class="span9">
		<h1><?php echo $this->escapeHtml($title); ?> 
	    <small> <a href="#helpModal" data-toggle="modal"><i class="icon-info-sign"> </i></a></small> </h1>
	</div>
	<?php if ($this->isAllowed('Parcours') === true) :?>
		<a href="<?php echo $this->url('parcours/ajouter') ;?>" class="btn btn-primary span3"><i class="icon-plus"></i> Ajouter un parcours</a>
	<?php endif; ?>
</div>

<div class="row-fluid">
    <div class="span12">
        <div>
            <table class="table table-striped table-bordered data">
                <thead>
                    <tr>
                        <th>Titre</th>
                        <th>Description</th>
                        <th>Visibilité</th>
                        <!-- <th> </th>  -->
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="3">En cours de téléchargement</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php 
$this->headScript()->appendFile($this->basePath() . '/js/pillbox.js') ;
$this->headScript()->appendFile($this->basePath() . '/js/jquery.dataTables.js');
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-confirm.js');
$this->headScript()->appendFile($this->basePath() . '/js/ResultSet.js');?>

<?php $this->inlineScript()->captureStart(); ?>
	var tableParcours;
	$(function() {
	
	    tableParcours = ResultSet.paginate(
	    	$('.data'),
			{
	         	"aoColumns": [
		           	           	null,
		           	           	{ "bSortable": false  },
		           	           	null,
	           	           	 ],
	           	"iColumns": 3,
	           	"bAutoWidth": false,
				"bSortClasses":false,
	           	"bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "<?php echo $this->url("parcours"); ?>",
    			"fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
    				var data = new Array();
    				if (data.length > 0) {
						aoData.push( { "name": "conditions", "value": JSON.stringify(data) } );
					}
      				oSettings.jqXHR = $.ajax( {
	        			"dataType": 'json',
	        			"type": "POST",
	        			"url": sSource,
	        			"data": aoData,
	        			"success": fnCallback
	     			});
	     		},
	     		"fnDrawCallback": function(oSettings, json){
	     			$(".href-type-element").unbind("click").bind("click", function(e) {
						window.open($(this).attr("href"), "_blank");
						e.preventDefault();
					});
	     		}
			}
		);
	});
	
<?php $this->inlineScript()->captureEnd(); ?>
