<?php 
if($this->statut):
	if($this->source == "password"): ?>
		<div class="alert alert-success">Le mot de passe a été modifié avec succès.</div>
	<?php endif;
endif;

$title = 'Mon compte';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css');
?>

<div class="message"></div>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
</div>

<div class="row-fluid">
	<div class="span6 well">
		<h4>Profil</h4>
	    <div class="row-fluid">
		    <div class="span6">
		    	<a class="thumbnail"><img src="http://critterapp.pagodabox.com/img/user.jpg" alt=""></a>
		    	<a href="<?php echo $this->url('zfcuser/logout') ?>" role="button" class="btn btn-danger btn-block" >
		    	<i class="icon-off"></i>  Déconnexion</a>
		    </div>
		    <div class="span6">
	    		<blockquote>
		    		<address>
						<strong>
							<i class="icon-user"></i> 
							<span id="displayName" class="text CursorPointer" 
		                        data-url="<?php echo $this->url("admin/changeProfileInfosAjax"); ?>" 
		                        data-value="<?php echo $this->escapeHtml($this->zfcUserDisplayName()); ?>" data-placement="right" data-type="text" data-pk="1">
		                        <?php echo $this->escapeHtml($this->zfcUserDisplayName()); ?>
                    		</span>
						</strong>
						<br/>
						
						<i class="icon-globe"></i> 
						<span id="adresse" class="text CursorPointer" 
	                        data-url="<?php echo $this->url("admin/changeProfileInfosAjax"); ?>" 
	                        data-value="<?php echo $this->escapeHtml($this->zfcUserIdentity()->getAdresse()); ?>" data-placement="right" data-type="text" data-pk="1">
	                        <?php echo $this->escapeHtml($this->zfcUserIdentity()->getAdresse()); ?>
                    	</span>
                    	<br/>
                    	
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						<span id="code_postal" class="text CursorPointer" 
	                        data-url="<?php echo $this->url("admin/changeProfileInfosAjax"); ?>" 
	                        data-value="<?php echo $this->escapeHtml($this->zfcUserIdentity()->getCodePostal()); ?>" data-placement="right" data-type="text" data-pk="1">
	                        <?php echo $this->escapeHtml($this->zfcUserIdentity()->getCodePostal()); ?>
	                    </span>
                    	
                    	&nbsp;
						<span id="ville" class="text CursorPointer" 
	                        data-url="<?php echo $this->url("admin/changeProfileInfosAjax"); ?>" 
	                        data-value="<?php echo $this->escapeHtml($this->zfcUserIdentity()->getVille()); ?>" data-placement="right" data-type="text" data-pk="1">
	                        <?php echo $this->escapeHtml($this->zfcUserIdentity()->getVille()); ?>
                    	</span>
                    	<br/>
                    	
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						<span id="pays" class="text CursorPointer" 
	                        data-url="<?php echo $this->url("admin/changeProfileInfosAjax"); ?>" 
	                        data-value="<?php echo $this->escapeHtml($this->zfcUserIdentity()->getPays()); ?>" data-placement="right" data-type="text" data-pk="1">
	                        <?php echo $this->escapeHtml($this->zfcUserIdentity()->getPays()); ?>
                    	</span>
                    	<br/>
						
						<i class="icon-phone"></i> 
						<span id="telephone" class="text CursorPointer" 
	                        data-url="<?php echo $this->url("admin/changeProfileInfosAjax"); ?>" 
	                        data-value="<?php echo $this->escapeHtml($this->zfcUserIdentity()->getTelephone()); ?>" data-placement="right" data-type="text" data-pk="1">
	                        <?php echo $this->escapeHtml($this->zfcUserIdentity()->getTelephone()); ?>
                    	</span>
                    	<br/>
						
						<i class="icon-envelope"></i>
						<span id="email" class="text CursorPointer" 
	                        data-url="<?php echo $this->url("admin/changeProfileInfosAjax"); ?>" 
	                        data-value="<?php echo $this->escapeHtml($this->zfcUserIdentity()->getEmail()); ?>" data-placement="right" data-type="text" data-pk="1">
	                        <?php echo $this->escapeHtml($this->zfcUserIdentity()->getEmail()); ?>
                    	</span>

					</address>
				</blockquote>		
				<a href="<?php echo $this->url('zfcuser/changepassword'); ?>" role="button" class="btn btn-primary btn-block"> <i class="icon-pencil"></i>  Changer mon mot de passe </a>
		    </div>
	    </div>
	</div>
	
	<div class="span6 well">
	    <h4>Droits</h4>
	    
	    <div class="row-fluid">
		    <div class="span6">
		    	<p> 
		    		Vous avez le rôle 
			    	<strong>
				    	<?php 
				    	$roles = $this->zfcUserIdentity()->getRoles();
				    	$role = $roles[0]->getRoleId(); 
						echo $role; ?>
					</strong>
				</p>
				<?php 
				if ($this->zfcUserIdentity()->getAttenteRole()) {
					echo '<p>Votre demande de role "<strong>'.$this->zfcUserIdentity()->getAttenteRole()->getRoleId().'</strong>" bien été prise en compte. </p>';
				}
				?>
		    </div>
		    
		    <div class="span6">
		    	<?php 
		    	if($role != 'Admin'){
		    		$rolesFils = array($role,'Visiteur');
		    	 	echo $this->demandeRole($rolesFils);
           		} 
           		?>
		    </div>
		</div>
		<br/>
		<div class="alert alert-info">
	    	<p class="lead">Information</p>
    	    <dl class="dl-horizontal">
			   <dt>Rôle Visiteur</dt>
		    	<dd>Personne non identifiée : peut consulter la collection et les parcours</dd>
		   	 	<dt>Rôle Utilisateur</dt>
		    	<dd>Contributeur enregistré sans droits : peut consulter la collection et les parcours</dd>
			    <dt>Rôle Collection</dt>
			    <dd>Permet (en plus) d'alimenter la collection</dd>
			    <dt>Rôle Parcours</dt>
			    <dd>Permet (en plus) d'éditer des parcours</dd>
			    <dt>Rôle Modeleur</dt>
			    <dd>Permet (en plus) de modeler la structure de la collection numériques (types d'arefacts et de médias, champs qui les décrivent).</dd>
			    <dt>Rôle Admin</dt>
			    <dd>Tous les droits</dd>
		    </dl>
	    </div>
	</div>
</div>

<div style="clear:both;"></div>

<?php $this->inlineScript()->captureStart(); ?>
	var table;
	$(function() {
	
		$('.text').editable({ 
   		  	emptytext: "Vide",
			success: function(e) {
				var resp = jQuery.parseJSON(e);
						
				if(resp.status === 'error'){
					return resp.message;
				} else {
					$('.message').showInfos(resp.message, "success");
				}				

			}
		});

	});
<?php
$this->inlineScript()->captureEnd();

$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js');
?>