<?php
$title = 'Sémantiques des relations entre artefacts';
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-editable.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/datatable.css');
?>

<ul class="breadcrumb">
	<li><a href="<?php echo $this->url('page') ?>">Accueil</a> <span class="divider">/</span></li>
	<li><a href="<?php echo $this->url('collection') ?>">Collection Numérique</a> <span class="divider">/</span></li>
    <li class="active"> Structure : Gestion des sémantiques</li>
</ul>

<!-- Help Modal -->
<div id="helpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Aide</h3>
    </div>
    <div class="modal-body">
    	<p>
    	Dans la collection numérique, un artefact peut être reliés à plusieurs autres artefacts. Chaque relation doit être porteuse d'une sémantique, petit texte qui explique la logique de cette relation.
    	</p>
    	<p>
    	Pour avoir des sémantiques cohérentes, ces dernières sont prédéfinies et vous pouvez les gérer sur cette page en tant qu'administrateur de l'application.
    	Lorsqu'un utilisateur décidera de lier deux artefacts entre eux, il aura a choisir une sémantique parmis celle existantes.
    	</p>
    	<p>
    	Une sémantique dépend des types d'artefacts que l'ont relie. Vous pouvez ici modifier ou supprimer une sémantique existante, et en créer de nouvelles.
    	</p>
    </div>
    <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Retour</button>
    </div>
</div>

<div class="page-header row-fluid">
	<div class="span9">
		<h1><?php echo $this->escapeHtml($title); ?> 
	    <small> <a href="#helpModal" data-toggle="modal"><i class="icon-info-sign"> </i></a></small> </h1>
	</div>
	<a href="<?php echo $this->url('semantique/ajouter') ;?>" class="btn btn-primary span3"><i class="icon-plus"></i> Ajouter une sémantique</a>
</div>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div>
            	<form id="form-multi" name="form-multi" class="">
	                <table class="table table-striped table-bordered data">
	                    <thead>
	                        <tr>
	                            <th>
	                            	<div class="span4">
							            <div class="input-prepend input-append">
							                <span class="add-on"><i class="icon-tag"> </i></span>
							                <select class="form-type-origine">
							                    <option class="type-all" data-type="" data-value="" >Tous types d'origines</option>
							                    <?php 
							                        foreach ($TypesOrigines as $TypeOrigine){
							                            echo '<option data-type="type_origine" data-value="'.$TypeOrigine['id'].'" >'.$this->escapeHtml($TypeOrigine['nom']).'</option>';
							                        }
							                    ?>
							                </select>
							                <button class="btn btn-success form-plus-type" type="button"><i class="icon-caret-right"> </i></button>
							            </div>
							        </div>
	                            </th>
	                            <th>Sémantique</th>
	                            <th>Description</th>
	                            <th>
	                            	<div class="span4">
							            <div class="input-prepend input-append">
							                <span class="add-on"><i class="icon-tag"> </i></span>
							                <select class="form-type-destination">
							                    <option class="type-all" data-type="" data-value="" >Tous types de destinations</option>
							                    <?php 
							                        foreach ($TypesDestinations as $TypeDestination){
							                            echo '<option data-type="type_destination" data-value="'.$TypeDestination['id'].'" >'.$this->escapeHtml($TypeDestination['nom']).'</option>';
							                        }
							                    ?>
							                </select>
							                <button class="btn btn-success form-plus-type" type="button"><i class="icon-caret-right"> </i></button>
							            </div>
							        </div>
	                            </th>
	                            <th>&nbsp;</th>
	                        </tr>
	                    </thead>
	                    <tbody>
	                        <tr>
	                            <td colspan="6">En cours de téléchargement</td>
	                        </tr>
	                    </tbody>
	                </table>
	        	</form>
            </div>
        </div>
    </div>
</div>

<!-- Contiendra la pop-up de confirmation lors d'un clic sur un bouton 'supprimer' -->
<div id="confirmDiv" >
</div>

<?php 
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-editable.js');
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap-confirm.js');
$this->headScript()->appendFile($this->basePath() . '/js/jquery.dataTables.js');
$this->headScript()->appendFile($this->basePath() . '/js/ResultSet.js');
//$this->headScript()->appendFile($this->basePath() . '/js/pillbox.js') ;

$this->inlineScript()->captureStart(); ?>
	var table;

    $(function() {

        table = ResultSet.paginate(
            $('.data'),
            {
                "aoColumns": [
                                { "bSortable": false  },
                                null, 
                                null,
                                { "bSortable": false  },
                                { "bSortable": false  }
                             ],
                "iColumns": 4,
                "bAutoWidth": false,
                "bSortClasses":false,
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "<?php echo $this->url("semantique"); ?>",
                "fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
                    
                    var data                    = new Array();
                    
                    var typeOrigine             = $('.form-type-origine > option:selected');
                    var typeDestination         = $('.form-type-destination > option:selected');

		            var objTypeOrigine          =  new Object();
                    objTypeOrigine["type"]      = typeOrigine.attr('data-type');
                    objTypeOrigine["value"]     = typeOrigine.attr('data-value');

		            var objTypeDestination      =  new Object();
                    objTypeDestination["type"]  = typeDestination.attr('data-type');
                    objTypeDestination["value"] = typeDestination.attr('data-value');

					if( objTypeOrigine["type"] != '' && objTypeOrigine["value"]){
						data.push(objTypeOrigine);
					}

					if( objTypeDestination["type"] != '' && objTypeDestination["value"]){
						data.push(objTypeDestination);
					}

                    if (data.length > 0) {
                        aoData.push( { "name": "conditions", "value": JSON.stringify(data) } );
                    }

                    oSettings.jqXHR = $.ajax( {
                        "dataType": 'json',
                        "type": "POST",
                        "url": sSource,
                        "data": aoData,
                        "success": fnCallback
                    });
                },
                "fnDrawCallback": function () {
                	// Modale de confirmation pour la suppression d'un sémantique
                    $(".SupprimerSemantique").click(function(event){
                        var dateURL = $(this).attr('data-url');
                        var dateValue = $(this).attr('data-value');
                        $('#confirmDiv').confirmModal({
                            heading:'Confirmation',
                            body:"Êtes-vous sûr de vouloir supprimer définitivement la sémantique <br> \""+dateValue+"\" ?",
                            callback: function() {
                                $.post(
                                    dateURL,
                                    { name: "supprimer" },
                                    function(response) {
                                    	document.location.reload();
                                        /*$("#data").dataTable().fnDraw();*/
                                    }
                                );
                            }
                        });   
                    });
                    $('.edit').editable({ mode: 'inline', emptytext: 'Vide'});
                }
            }
        );

        $(".form-plus-type").click( function () {
            table.fnDraw();
            return false;
        });

	});
<?php $this->inlineScript()->captureEnd(); ?>
