
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Créer un nouveau type d'élément</h3>
  </div>
  <div class="modal-body">
    
	<?php

	$form = $this->form;

	$form->setAttribute('class','ajTypeMediaForm form-horizontal no-submit');
	$form->get('nom')->setAttribute('placeholder','Nom')->setLabelAttributes(array('class' => 'control-label'));

	$form->get('submit')->setLabel('Valider')->setAttribute('class','ajChampSubmit btn btn-primary');

	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id')); ?>

	<div class="control-group">
		<?php echo $this->formLabel($form->get('nom')) ?>
		<div class="controls">
		<?php echo $this->formInput($form->get('nom')) ?>
		<?php echo $this->formElementErrors($form->get('nom')) ?>
		</div>
	</div>

	  <div class="modal-footer">
	  	<a href="#" class="btn btn-primary ajTypeMediaSubmit">Créer</a>
	  	<button class="btn" data-dismiss="modal" aria-hidden="true">Annuler</button>
	<?php //  echo $this->formSubmit($form->get('submit')); ?>
	</div>
	<?php echo $this->form()->closeTag();?>
</div>

