<?php
$title = 'Changer mon mot de passe';
$this->headTitle($title);

if ($status === true) : ?>
    <!-- <div class="alert alert-success">L'adresse Email a été modifiée avec succès.</div> <!-- -->
    <!-- 
    <script type="text/javascript">
        function delayer(){
            window.location = "/user";
        }
        setTimeout('delayer()', 3000);
    </script>
    <!-- -->
    <?php //include 'index.phtml'; ?>
    <script type="text/javascript">
        $(location).attr('href', '<?php echo $this->url("zfcuser", array("statut"=>true, "source"=>"password")); ?>');
    </script>

<?php else : ?>
	<div class="page-header">
	    <h1><?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
	</div>

	<?php if ($status === false) : ?>
		<div class="alert alert-error">Impossible de modifier le mot de passe. Veuillez réessayer.</div>
	<?php endif; ?>
	<?php
	
	$form = $this->changePasswordForm;
	
	$form->prepare();
	$form->setAttribute('action', $this->url('zfcuser/changepassword'));
	$form->setAttribute('method', 'post');
	$form->setAttribute('class','form-horizontal');
	$form->get('newCredential')->setLabel('Nouveau mot de passe')->setAttribute('placeholder','******')->setLabelAttributes(array('class' => 'control-label'));
	$form->get('newCredentialVerify')->setLabel('Confirmation')->setAttribute('placeholder','******')->setLabelAttributes(array('class' => 'control-label'));
	$form->get('credential')->setLabel('Mot de passe')->setAttribute('placeholder','******')->setLabelAttributes(array('class' => 'control-label'));
	$form->get('submit')->setValue('Valider')->setAttribute('class','btn btn-primary');
	
	$emailElement = $form->get('identity');
	$emailElement->setValue($this->zfcUserIdentity()->getEmail());
	
	echo $this->form()->openTag($form);
	?>
	
	<?php echo $this->formElementErrors($form->get('identity')); ?>
	<?php echo $this->formInput($form->get('identity')); ?>
	
	<div class="control-group">
		<?php echo $this->formLabel($form->get('credential')); ?>
		<div class="controls">
			<?php
			echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
			?>
		</div>
	</div>
		
	<div class="control-group">
		<?php echo $this->formLabel($form->get('newCredential')); ?>
		<div class="controls">
			<?php
			echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
			?>
		</div>
	</div>
		
	<div class="control-group">
		<?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
		<div class="controls">
			<?php
			echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
			?>
		</div>
	</div>
	
	<div class="form-actions">
		<?php
		echo $this->formInput($form->get('submit'));
		?>
		<a href="/user" role="button" class="btn"> Annuler </a>
	</div>
	<?php echo $this->form()->closeTag();
endif; ?>