<?php
$title = 'Login';
$this->headTitle($title);
?>

<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?> <!-- <small>Subtext for header</small> --></h1>
</div>

<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url("zfcuser/login"); ?>">Connexion</a></li>
    <li class="active"><a href="<?php echo $this->url("zfcuser/register"); ?>">Inscription</a></li>
</ul>

<div class="tab-content">
	<div class="row-fluid">
		<div class="span6">
			<h3>Inscription</h3>
			<?php
				$form = $this->registerForm;
				$form->prepare();
				
				$form->setAttribute('action', $this->url('zfcuser/register'));
				$form->setAttribute('method', 'post');
				$form->setAttribute('class','form-horizontal');
				
				$form->get('display_name')->setAttribute('placeholder','Nom Prénom')->setLabel('Nom / prénom');
				$form->get('email')->setAttribute('placeholder','exemple@exemple.fr');
				$form->get('username')->setAttribute('placeholder','Login')->setLabel('Login');
				
				$form->get('password')->setAttribute('placeholder','******')->setLabel('Mot de passe');
				$form->get('passwordVerify')->setAttribute('placeholder','******')->setLabel('Vérification mot de passe');

				$form->get('telephone')->setAttribute('placeholder','0600000000');
				$form->get('adresse')->setAttribute('placeholder','12 rue Joseph REY');
				$form->get('code_postal')->setAttribute('placeholder','38000');
				$form->get('ville')->setAttribute('placeholder','Grenoble');
				$form->get('pays')->setAttribute('placeholder','France');
				
				$form->get('submit')->setLabel('Valider')->setAttribute('class','btn btn-primary');

				$form->get('checkboxAgreement')->setLabel('J\'accepte les conditions générales du projet CERVIN')->setAttribute('required', true);
				
				echo $this->form()->openTag($form);
			?>
		    <fieldset>
		    <?php foreach ($form as $element): ?>
		    
		        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
		        <div class="control-group">
		            <?php echo $this->formLabel($element->setLabelAttributes(array('class' => 'control-label'))); ?>
		        <?php endif ?>
		        
		        <?php if ($element instanceof Zend\Form\Element\Button): ?>
		        
		            <div class="form-actions">
		                <?php echo $this->formButton($element) ?>
		                
		        <?php elseif ($element instanceof Zend\Form\Element\Checkbox): ?>
		
		            <div class="controls"><?php echo $this->formCheckbox($element).$this->formElementErrors($element);?></div>
		
		        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
		        
		            <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></div>
		            
		        <?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
		        
		            <div class="controls"><?php echo $this->formTextarea($element->setAttribute('class', 'span10')) . $this->formElementErrors($element) ?></div>

		        <?php else: ?>
		        
		            <div class="controls"><?php echo $this->formInput($element->setAttribute('class', 'span10')) . $this->formElementErrors($element) ?></div>
		            
		        <?php endif ?>
		        
		        </div>
		    <?php endforeach ?>
		    </fieldset>
		    <?php if ($this->redirect): ?>
		        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
		    <?php endif ?>
		    <?php echo $this->form()->closeTag() ?>
	    </div>
	    <div class="span6">
	    	<h3>Conditions générales</h3>
	    	<div class="conditionsG" >
	    		<?php echo $this->ConditionsGenerales(); ?>
	    	</div>
	    </div>
	</div>
</div>


<!--
<form class="form-horizontal">
    <fieldset>
    
        <legend>Inscription</legend>
        
        <div class="control-group">
            <label class="control-label">Nom</label>
            <div class="controls">
                <input id="nom" name="nom" placeholder="Nom" class="input-xlarge" required="" type="text">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label">Prenom</label>
            <div class="controls">
                <input id="prenom" name="prenom" placeholder="Prenom" class="input-xlarge" required="" type="text">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label">Email</label>
            <div class="controls">
                <input id="email" name="email" placeholder="Email" class="input-xlarge" required="" type="text">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Mots de passe</label>
            <div class="controls">
                <input id="password" name="password" placeholder="Mot de passe " class="input-xlarge" required="" type="password">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label">Confirmation</label>
            <div class="controls">
                <input id="confirmation" name="confirmation" placeholder="Confirmation" class="input-xlarge" required="" type="password">
            </div>
        </div>
        <div class="form-actions">
        
        <button class="btn btn-success">Inscription</button>
        
        </div>
    </fieldset>
</form>
<!-- -->